name: Update README with YouTube Videos

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update README
        uses: GalvinPython/youtube-readme@1.0
        with:
          youtube_channel_id: 'UCW4PLi-ObJt3m6YTSEQY3gw'  # Find in YouTube Studio
          readme_file_path: 'README.md'
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "chore: update YouTube videos" || echo "No changes"
          git push